### ISSUE TITLE
What does this send to Supabase?

### ISSUE THREAD

**Issue by xet7** [yashs662/rust_kanban#10]
Hi,
what does this send to Supabase?

https://github.com/yashs662/rust_kanban/blob/main/src/constants.rs#L47-L48

**Comment by yashs662** [comment]
The JSON board data is stored in supabase to allow for syncing between devices along with a user id that is generated once you sign up. currently, this is NOT ENCRYPTED!!! so I (the admin) will be able to see your data so please do not put anything sensitive up there. I am working on end-to-end encryption for this data and it will be coming soon. so only you will be able to decode your own data and I would not be able to see anything.

**Comment by yashs662** [comment]
There is RLS in place. so rest assured once encryption is in place your data will be safe and only you will be able to access it
