### ISSUE TITLE
Cargo.lock

### ISSUE THREAD

**Issue by 0323pin** [yashs662/rust_kanban#12]
**Is your feature request related to a problem? Please describe.**
I wonder if you want to make my life easier as package maintainer and remove `Cargo.lock` from `.gitignore`. We (NetBSD) have a script that reads `Cargo.lock` to automatically list all the dependency crates.
If `Cargo.lock` isn't present in the repository, I have to this manually.

**Additional context**
I've just packaged `rust-kanban` for NetBSD and merged the package into the main branch. Commit log for reference, http://mail-index.netbsd.org/pkgsrc-changes/2023/09/13/msg282489.html

Pre-compiled binaries will be available for users by the end of this month.

Regards

**Comment by yashs662** [comment]
Sure! Thank you so much for doing this

**Comment by 0323pin** [comment]
Thx!
