### ISSUE TITLE
Any non-ASCII characters comes with an extra space when typed

### ISSUE THREAD

**Issue by GrimPixel** [yashs662/rust_kanban#16]
**Describe the bug**
Any non-ASCII characters comes with an extra space when typed

**To Reproduce**
1. Type an non-ASCII character, like ä.

**Expected behavior**
It's `ä` instead of `ä `.

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by yashs662** [comment]
Yeah, that is a side effect of using the old user input system, I am in the process of porting all of the user input fields to the new system (used in the card description field for eg when viewing a card) + a little bit of rewrite so it's taking a little while. Should be out soon. Please let me know if that is happening in the card description as well. It does not happen for me
