### ISSUE TITLE
Card description display didn't take line number display width into consideration

### ISSUE THREAD

**Issue by ZSCL22** [yashs662/rust_kanban#17]
**Describe the bug**
Card Description display, in popup card view and line number enabled, didn't take line number display width into consideration

**To Reproduce**
In popup card view, focusing on card description, in input mode, input a line longer than the box width. When moving cursor over the right boundary, the cursor would disappear and the line won't move to the left immediately.

**Expected behavior**
When cursor moves out of boundary, the line display should change accordingly(in the above case, move to the left/or wrap around so that cursor is always in the view)

**Desktop (please complete the following information):**
 - OS: Ubuntu

**How to fix it**
When computing "top_col", reduce the box width by the width from line number display.
The following seems to fix it:

In TextBoxRenderer::text
```
- -   let lnum_len = num_digits(lines_len);
- +   let lnum_len = num_digits(lines_len + 1);
```

When implement Widget for TextBoxRenderer,
``` 
--   let top_col = next_scroll_top(top_col, cursor.1 as u16, width);
-+	let top_col = if self.0.line_number_style().is_none() {
	    next_scroll_top(top_col, cursor.1 as u16, width)
	} else {
	    // when line number is dislayed, the width for text content is reduced
	    // the current display is format!("{}{}) ", pad, row + 1); 
	    // so the reduced amount is: max # of line number digits + 2, where "2" accounts for the ending ") ".            
	    let reduced_len = num_digits(self.0.lines().len()) as u16 + 2;
	    next_scroll_top(top_col, cursor.1 as u16, **width - reduced_len**)
	};
```

In TextLineFormatter::line_number
```
--   let pad = spaces(lnum_len - num_digits(row + 1) + 1);
-+   let pad = spaces(lnum_len - num_digits(row + 1));
```

**Comment by yashs662** [comment]
Yes, I too discovered this while porting all of the input fields to behave coherently, a fix is coming in the next release!

**Comment by ZSCL22** [comment]
Thanks and look forward to it! 
BTW, I very much enjoy using it. Great work!
