### ISSUE TITLE
can't build rust_kanban 

### ISSUE THREAD

**Issue by Horryportier** [yashs662/rust_kanban#6]
**Describe the bug**
i have an issue with building this crate. this is the output of  the `cargo build` [log.txt](https://github.com/yashs662/rust_kanban/files/11750288/log.txt) .
Its a issue when there are to different ratatui packages that create conflicts. I've had this issue in my project but it been resolved by `rm -rf ~/.cargo/registry` but its not the case with this crate. 

**To Reproduce**
I've tried  to install using `cargo install --git https://github.com/yashs662/rust_kanban` and by forking and cloning this repo. 

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS x86_64
 - Browser  firefox

**Additional context**
I've seen that the project wasn't updated in a while which tells me that it might be issue with changes in `ratatui` that need to be updated but I'm not sure as somewhat similar bug happens to me although methods to solve that problem don't work on this one.

**Comment by yashs662** [comment]
I have been busy IRL so haven't updated the project in a while. Will look into your problem 😊
