### ISSUE TITLE
Ratatui v.next has a serialization breaking change

### ISSUE THREAD

**Issue by joshka** [yashs662/rust_kanban#8]
I noticed that you're using serde for deserializing ratatui types - Just a quick heads up of the upcoming change in the next version: https://github.com/tui-rs-revival/ratatui/pull/205. I haven't dug into the source to check, so I'm not sure if this will affect your usage. (There's only two crates using the serde feature right now - yours and xplr)

**Comment by yashs662** [comment]
Thank you for the heads up!! 😊will look into this

**Comment by joshka** [comment]
P.s. (it's still not released due to holidays etc. :/)

**Comment by yashs662** [comment]
It's fine I don't think it will impact my project that much
